import type { Metadata } from 'next';
import { AppBar } from '@/_components';

export const metadata: Metadata = {
  title: 'Portfólio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <>
      <AppBar />
      {children}
    </>
  );
}
